from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.Input1 = QtWidgets.QLineEdit(Form)
        self.Input1.setGeometry(QtCore.QRect(10, 30, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.Input1.setFont(font)
        self.Input1.setAlignment(QtCore.Qt.AlignCenter)
        self.Input1.setObjectName("Input1")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(90, 40, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Input2 = QtWidgets.QLineEdit(Form)
        self.Input2.setGeometry(QtCore.QRect(180, 30, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.Input2.setFont(font)
        self.Input2.setAlignment(QtCore.Qt.AlignCenter)
        self.Input2.setObjectName("Input2")
        self.Result = QtWidgets.QLineEdit(Form)
        self.Result.setGeometry(QtCore.QRect(310, 30, 71, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.Result.setFont(font)
        self.Result.setAlignment(QtCore.Qt.AlignCenter)
        self.Result.setObjectName("Result")
        self.equal = QtWidgets.QLabel(Form)
        self.equal.setGeometry(QtCore.QRect(270, 50, 31, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.equal.setFont(font)
        self.equal.setObjectName("equal")
        self.Clear_btn = QtWidgets.QPushButton(Form)
        self.Clear_btn.setGeometry(QtCore.QRect(60, 130, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.Clear_btn.setFont(font)
        self.Clear_btn.setObjectName("Clear_btn")
        self.Calculate_btn = QtWidgets.QPushButton(Form)
        self.Calculate_btn.setGeometry(QtCore.QRect(230, 130, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Calculate_btn.setFont(font)
        self.Calculate_btn.setObjectName("Calculate_btn")

        self.retranslateUi(Form)
        self.Clear_btn.clicked.connect(self.Input1.clear)
        self.Clear_btn.clicked.connect(self.Input2.clear)
        self.Clear_btn.clicked.connect(self.Result.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "+"))
        self.comboBox.setItemText(1, _translate("Form", "-"))
        self.comboBox.setItemText(2, _translate("Form", "×"))
        self.comboBox.setItemText(3, _translate("Form", "÷"))
        self.equal.setText(_translate("Form", "="))
        self.Clear_btn.setText(_translate("Form", "Clear"))
        self.Calculate_btn.setText(_translate("Form", "Calculate"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())